-- ================================================================
-- 015_daily_recaps.sql
-- Stores one Claude-generated narrative per UTC day covering that
-- day's UK GTA RP scene activity.
--
-- Generated by the scheduler (or manually via POST /api/daily-recap)
-- and read by /gta-rp/digest/ ("Yesterday" section) plus the Discord
-- daily summary card.
-- ================================================================

CREATE TABLE IF NOT EXISTS daily_recaps (
  date           TEXT PRIMARY KEY,        -- 'YYYY-MM-DD' UTC, the day the recap covers
  content        TEXT NOT NULL,           -- the recap prose
  source         TEXT NOT NULL,           -- 'anthropic' | 'fallback'
  model          TEXT,                    -- e.g. 'claude-sonnet-4-6'
  data_snapshot  TEXT,                    -- JSON of the metrics handed to the LLM
  generated_at   INTEGER NOT NULL         -- unix seconds
);

CREATE INDEX IF NOT EXISTS idx_daily_recaps_generated ON daily_recaps(generated_at);
