-- ================================================================
-- 016_clip_of_day.sql
-- Stores one Claude-picked clip per UTC day. Generated by the
-- scheduler at 06:00 UTC, surfaced as a hero card on /gta-rp/clips/
-- and on the homepage live feed.
-- ================================================================

CREATE TABLE IF NOT EXISTS clip_of_day (
  date         TEXT PRIMARY KEY,        -- 'YYYY-MM-DD' UTC, the day the clip is from
  clip_id      TEXT NOT NULL,           -- Twitch clip slug
  clip_data    TEXT NOT NULL,           -- JSON of the chosen clip object
  caption      TEXT NOT NULL,           -- ~50-word AI-written caption
  picked_by    TEXT NOT NULL,           -- 'anthropic' | 'fallback'
  model        TEXT,                    -- e.g. 'claude-sonnet-4-6'
  candidates   TEXT,                    -- JSON of the 10-clip pool (for transparency)
  generated_at INTEGER NOT NULL         -- unix seconds
);

CREATE INDEX IF NOT EXISTS idx_clip_of_day_generated ON clip_of_day(generated_at);
